language: R
warnings_are_errors: true
sudo: false
cache: packages

addons:
    apt:
        packages:
            - valgrind
            - libudunits2-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_CODECOV=true
        - os: linux
          r: devel
          dist: trusty
        - os: linux
          r: oldrel
          dist: trusty
        - os: osx
          r: release
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true
    allow_failures:
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true
        - os: linux # checking GDAL version >= 2.0.0... no -> sf not compatible
          r: oldrel
          dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
    - Rscript -e "covr::codecov()"
