language: R
warnings_are_errors: true
sudo: required
cache: packages

addons:
    apt:
        packages:
            - libudunits2-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev

matrix:
    include:
        - os: linux
          r: release
          after_success:
              - Rscript -e "covr::codecov()"
        - os: linux
          r: devel
        - os: linux
          r: oldrel
        - os: osx
          r: release
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true
    allow_failures:
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true
        - os: linux # checking GDAL version >= 2.0.0... no -> sf not compatible
          r: oldrel
          dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
      - covr

